version: '3.5'

services:
  360-backend:
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - /node_modules/

  360-mongodb:
    image: mongo:4.1.7
    environment:
      - MONGO_INITDB_DATABASE=r360
