version: '3.5'
services:
  r360-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - /etc/r360/frontend/.env
    ports:
      - "3000"
    networks:
      - external_network
      - default

networks:
  external_network:
    external: true
