version: '3.5'

services:
  360-backend:
    build: .
    volumes:
      - ./:/var/www
      - ./.docker/nginx/config/development.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/supervisord/development.conf:/etc/supervisord.conf
      - /node_modules/
    ports:
      - 8080:80

  360-mongodb:
    volumes:
      - .docker/mongodb/data:/data/db

  storage-minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/360 && /usr/bin/minio server /data'
    ports:
      - "9000:9000"
    networks:
      - default
    volumes:
      - .docker/minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY