version: '3.5'

services:
  r360-frontend:
    image: node:10-alpine
    volumes:
      - ./:/var/www
    ports:
      - 8282:8080
    networks:
      - external_network
    command: sh -c "npm install && npm run build && npm run serve"
    working_dir: /var/www/frontend

  r360-backend:
    build: .
    volumes:
      - ./:/var/www
      - .docker/nginx/logs:/etc/logs/nginx
      - .docker/php/log:/var/log
    ports:
      - 8181:80
    networks:
      - external_network

  r360-mongodb:
    image: mongo:4.1.7
    volumes:
      - .docker/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=r360
    expose:
      - 27017
    networks:
      - external_network

networks:
  external_network:
