version: '3.5'

services:
  360-backend:
    build: .
    volumes:
      - ./:/var/www
      - ./.docker/nginx/config/development.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/supervisord/development.conf:/etc/supervisord.conf
      - /node_modules/
    ports:
      - 8080:80
    env_file: .env

  360-mongodb:
    volumes:
      - .docker/mongodb/data:/data/db
