version: '3.5'
services:
  r360-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm install && npm run dev"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - external_network
      - default

networks:
  external_network:
    external: true